Release 2.1.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.2
+# This script was automatically generated by ACR v1.3
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -41,7 +41,7 @@ done
 }
 
 VPATH=`dirname ${0}`
-if [ "${VPATH}" = "." ]; then 
+if [ "${VPATH}" = "." ]; then
 	WODIS=current
 else
 	if [ "${VPATH}" = "${PWD}" ]; then
@@ -103,12 +103,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2-extras' ; VERSION='2.0.0' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2-extras' ; VERSION='2.1.0' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
-                
+
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-extras-2.0.0 to adapt to many kinds of systems.
+'configure' configures radare2-extras-2.1.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -150,8 +150,8 @@ EOF2
 
 printf "
 Optional Features:
-  --with-ostype          Choose OS type ( gnulinux windows darwin haiku )  (USEROSTYPE=auto)
-  --without-ewf          build without libewf 
+  --with-ostype          Choose OS type ( gnulinux windows darwin haiku ) (USEROSTYPE=auto)
+  --without-ewf          build without libewf
 "
 printf "
 Some influential environment variables:
@@ -178,7 +178,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-extras-2.0.0 configuration script done with acr v1.2.
+echo "radare2-extras-2.1.0 configuration script done with acr v1.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -202,14 +202,14 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2-extras"
-echo "VERSION:   2.0.0"
+echo "VERSION:   2.1.0"
 echo "LANGS:     c"
 echo "OPTIONAL:  libewf"
 echo "PKG-CONFIG:  r_core libewf unicorn yara"
 echo "FLAGS:     --with-ostype=auto --without-ewf"
 	exit 0
 	;;
---cache-file) 
+--cache-file)
 	# ignored: acr have no cache
 	;;
 --build)
@@ -254,7 +254,7 @@ echo "FLAGS:     --with-ostype=auto --without-ewf"
 
 --with-ostype) if [ -z "${value}" ]; then USEROSTYPE="auto"; else USEROSTYPE="${value}" ; fi ;;
 "--without-ewf") WANT_EWF="0"; ;;
-*) if [ "$value" ]; then eval "`echo $flag2=$value`" ; 
+*) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
 }
@@ -286,7 +286,7 @@ echo "checking for working directories... ${WODIS}"
 echo "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
 
-: 
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -302,6 +302,7 @@ do_remove
 echo "ERROR: ${CC} cannot create executables" >&2 ;
 exit 1 ; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
@@ -329,9 +330,8 @@ if [ $? = 0 ]; then
 else
 	eval ${VAR}=0
 	echo no  ; fi }
-check_library HAVE_LIB_EWF ewf 0 
+check_library HAVE_LIB_EWF ewf 0
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for libewf... '
 tmp=`${PKGCONFIG} --cflags libewf 2>/dev/null`
 if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_LIBEWF=0; 
@@ -348,7 +348,6 @@ HAVE_LIB_EWF="0"; fi
 if [ "$WANT_EWF" = "0" ]; then
 HAVE_LIB_EWF="0"; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for unicorn... '
 tmp=`${PKGCONFIG} --cflags unicorn 2>/dev/null`
 if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_UNICORN=0; 
@@ -358,9 +357,8 @@ tmp=`${PKGCONFIG} --libs unicorn 2>/dev/null`
 if [ $? = 0 ]; then 
 echo yes; HAVE_PKGCFG_UNICORN=1; 
 UC_LDFLAGS=$tmp; fi; fi
-check_library HAVE_LIB_YARA yara 0 
+check_library HAVE_LIB_YARA yara 0
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for yara... '
 tmp=`${PKGCONFIG} --cflags yara 2>/dev/null`
 if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_YARA=0; 
@@ -374,7 +372,7 @@ SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
 	[ "${A}" = VPATH ] && continue
-	[ "${A}" = srcdir ] && continue 
+	[ "${A}" = srcdir ] && continue
 	eval "VAR=\$${A}"
 	VAR="`echo ${VAR} | sed -e 's/\,/\\\,/g'`"
 	[ $COUNT = 10 ] && COUNT=0 && SEDFLAGS="${SEDFLAGS}' -e '"
diff --git a/keystone/configure b/keystone/configure
--- a/keystone/configure
+++ b/keystone/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.2
+# This script was automatically generated by ACR v1.3
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -39,7 +39,7 @@ done
 }
 
 VPATH=`dirname ${0}`
-if [ "${VPATH}" = "." ]; then 
+if [ "${VPATH}" = "." ]; then
 	WODIS=current
 else
 	if [ "${VPATH}" = "${PWD}" ]; then
@@ -103,7 +103,7 @@ done
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
  PKGNAME='radare2-keystone' ; VERSION='0.1' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
-                
+
 show_usage() {
 cat <<EOF2
 'configure' configures radare2-keystone-0.1 to adapt to many kinds of systems.
@@ -175,7 +175,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-keystone-0.1 configuration script done with acr v1.2.
+echo "radare2-keystone-0.1 configuration script done with acr v1.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -205,7 +205,7 @@ echo "REQUIRED:  libkeystone"
 echo "PKG-CONFIG:  r_asm"
 	exit 0
 	;;
---cache-file) 
+--cache-file)
 	# ignored: acr have no cache
 	;;
 --build)
@@ -248,7 +248,7 @@ echo "PKG-CONFIG:  r_asm"
 --mandir)
 	MANDIR="$value"; ;;
 
-*) if [ "$value" ]; then eval "`echo $flag2=$value`" ; 
+*) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
 }
@@ -282,7 +282,7 @@ ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
 
 
 
-: 
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -333,8 +333,9 @@ else
   echo "this library is required."
   do_remove
   exit 1 ; fi }
-check_library HAVE_LIB_KEYSTONE keystone 1 
+check_library HAVE_LIB_KEYSTONE keystone 1
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_asm... '
 tmp=`${PKGCONFIG} --cflags r_asm 2>/dev/null`
@@ -351,7 +352,7 @@ SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
 	[ "${A}" = VPATH ] && continue
-	[ "${A}" = srcdir ] && continue 
+	[ "${A}" = srcdir ] && continue
 	eval "VAR=\$${A}"
 	VAR="`echo ${VAR} | sed -e 's/\,/\\\,/g'`"
 	[ $COUNT = 10 ] && COUNT=0 && SEDFLAGS="${SEDFLAGS}' -e '"
diff --git a/yara/yara/configure b/yara/yara/configure
--- a/yara/yara/configure
+++ b/yara/yara/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.2
+# This script was automatically generated by ACR v1.3
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -39,7 +39,7 @@ done
 }
 
 VPATH=`dirname ${0}`
-if [ "${VPATH}" = "." ]; then 
+if [ "${VPATH}" = "." ]; then
 	WODIS=current
 else
 	if [ "${VPATH}" = "${PWD}" ]; then
@@ -103,7 +103,7 @@ done
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
  PKGNAME='radare2-extras-yara' ; VERSION='1.0' ; CONTACT_MAIL="judy.frankowski@gmail.com" ; CONTACT_NAME="jfrankowski" ; CONTACT="jfrankowski <judy.frankowski@gmail.com>" ;
 }
-                
+
 show_usage() {
 cat <<EOF2
 'configure' configures radare2-extras-yara-1.0 to adapt to many kinds of systems.
@@ -171,7 +171,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-extras-yara-1.0 configuration script done with acr v1.2.
+echo "radare2-extras-yara-1.0 configuration script done with acr v1.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -201,7 +201,7 @@ echo "REQUIRED:  libyara"
 echo "PKG-CONFIG:  yara r_core"
 	exit 0
 	;;
---cache-file) 
+--cache-file)
 	# ignored: acr have no cache
 	;;
 --build)
@@ -244,7 +244,7 @@ echo "PKG-CONFIG:  yara r_core"
 --mandir)
 	MANDIR="$value"; ;;
 
-*) if [ "$value" ]; then eval "`echo $flag2=$value`" ; 
+*) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
 }
@@ -276,7 +276,7 @@ echo "checking for working directories... ${WODIS}"
 echo "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
 
-: 
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -309,8 +309,9 @@ else
   echo "this library is required."
   do_remove
   exit 1 ; fi }
-check_library HAVE_LIB_YARA yara 1 
+check_library HAVE_LIB_YARA yara 1
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for yara... '
 tmp=`${PKGCONFIG} --cflags yara 2>/dev/null`
@@ -324,7 +325,6 @@ if [ $? = 0 ]; then
 echo yes; HAVE_PKGCFG_YARA=1; 
 YR_LDFLAGS=$tmp; fi; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
 if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_CORE=0; 
@@ -340,7 +340,7 @@ SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
 	[ "${A}" = VPATH ] && continue
-	[ "${A}" = srcdir ] && continue 
+	[ "${A}" = srcdir ] && continue
 	eval "VAR=\$${A}"
 	VAR="`echo ${VAR} | sed -e 's/\,/\\\,/g'`"
 	[ $COUNT = 10 ] && COUNT=0 && SEDFLAGS="${SEDFLAGS}' -e '"
