Remove old yara 2 support

diff --git a/yara/yara/configure b/yara/yara/configure
--- a/yara/yara/configure
+++ b/yara/yara/configure
@@ -100,12 +100,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2-extras-yara2' ; VERSION='0.10.2-git' ; CONTACT_MAIL="julien.voisin@dustri.org" ; CONTACT_NAME="jvoisin" ; CONTACT="jvoisin <julien.voisin@dustri.org>" ;
+ PKGNAME='radare2-extras-yara' ; VERSION='1.0' ; CONTACT_MAIL="judy.frankowski@gmail.com" ; CONTACT_NAME="jfrankowski" ; CONTACT="jfrankowski <judy.frankowski@gmail.com>" ;
 }
                 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-extras-yara2-0.10.2-git to adapt to many kinds of systems.
+'configure' configures radare2-extras-yara-1.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -156,7 +156,7 @@ Some influential environment variables:
   CPP         C preprocessor
 "
 printf "
-Report bugs to: jvoisin <julien.voisin@dustri.org>"
+Report bugs to: jfrankowski <judy.frankowski@gmail.com>"
 echo ""
 exit 0
 }
@@ -169,7 +169,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-extras-yara2-0.10.2-git configuration script done with acr v0.10.2.
+echo "radare2-extras-yara-1.0 configuration script done with acr v0.10.2.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -192,11 +192,11 @@ case $flag in
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
-echo "PKGNAME:   radare2-extras-yara2"
-echo "VERSION:   0.10.2-git"
+echo "PKGNAME:   radare2-extras-yara"
+echo "VERSION:   1.0"
 echo "LANGS:     c"
 echo "REQUIRED:  libyara"
-echo "PKG-CONFIG:  r_core"
+echo "PKG-CONFIG:  yara r_core"
 	exit 0
 	;;
 --cache-file) 
@@ -257,7 +257,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C HAVE_LIB_YARA R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU PKGNAME VPATH VERSION CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C HAVE_LIB_YARA YR_CFLAGS YR_LDFLAGS HAVE_PKGCFG_YARA R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE"
 
 create_environ
 
@@ -306,6 +306,19 @@ else
   do_remove
   exit 1 ; fi }
 check_library HAVE_LIB_YARA yara 1 
+[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+echo 'Using PKGCONFIG: '${PKGCONFIG}
+printf 'checking pkg-config flags for yara... '
+tmp=`${PKGCONFIG} --cflags yara 2>/dev/null`
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_YARA=0; 
+echo 'This package is required'
+exit 1
+else 
+YR_CFLAGS=$tmp; 
+tmp=`${PKGCONFIG} --libs yara 2>/dev/null`
+if [ $? = 0 ]; then 
+echo yes; HAVE_PKGCFG_YARA=1; 
+YR_LDFLAGS=$tmp; fi; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
